version: '3.7'

services:
  authservice-db:
    image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
    restart: unless-stopped
    ports:
      - "14330:1433"
    volumes:
      - authservicedbdata:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd123
      MSSQL_PID: Express
      NAME: authservice-db

volumes:
  authservicedbdata: